using System;
using System.Runtime.Serialization;

namespace Rabbot.Jedi.Data.Entities.Exceptions
{
    public class JediDataIdNotGenerateByInsertException : JediException
    {
        public const string RABBOT_DETAUL_MESSAGE = "Id from entity '{0}' not was generated by insert method";
        public const string RABBOT_ERROR_CODE = "ERROR_ID_NOT_GENERATE";

        public string EntityName { get; }
        public JediDataIdNotGenerateByInsertException(string entityName)
            : base(string.Format(RABBOT_DETAUL_MESSAGE, entityName))
        {
            EntityName = entityName;
            Init();
        }
        public JediDataIdNotGenerateByInsertException(string entityName, string message)
            : base($"{string.Format(RABBOT_DETAUL_MESSAGE, entityName)}. {message}")
        {
            EntityName = entityName;
            Init();
        }
        public JediDataIdNotGenerateByInsertException(string entityName, Exception innerException)
            : base(string.Format(RABBOT_DETAUL_MESSAGE, entityName), innerException)
        {
            EntityName = entityName;
            Init();
        }

        protected JediDataIdNotGenerateByInsertException(SerializationInfo info, StreamingContext context) : base(info, context)
        {
            EntityName = string.Empty;
        }

        private void Init()
        {
            ErrorCode = RABBOT_ERROR_CODE;
            HttpStatusCode = 400;
        }
    }
}
