using Music.IO.Core.Exceptions;
using System;
using System.Globalization;
using System.Runtime.Serialization;

namespace Music.IO.Data.Entities.Exceptions
{
    public class IODataIdNotGenerateByInsertException : IOException
    {
        public const string Music_DETAUL_MESSAGE = "Id from entity '{0}' not was generated by insert method";
        public const string Music_ERROR_CODE = "ERROR_ID_NOT_GENERATE";

        public string EntityName { get; }
        public IODataIdNotGenerateByInsertException(string entityName) 
            : base(string.Format(Music_DETAUL_MESSAGE, entityName))
        {
            EntityName = entityName;
            Init();
        }
        public IODataIdNotGenerateByInsertException(string entityName, string message)
            : base($"{string.Format(Music_DETAUL_MESSAGE, entityName)}. {message}")
        {
            EntityName = entityName;
            Init();
        }
        public IODataIdNotGenerateByInsertException(string entityName, Exception innerException) 
            : base(string.Format(Music_DETAUL_MESSAGE, entityName), innerException)
        {
            EntityName = entityName;
            Init();
        }

        protected IODataIdNotGenerateByInsertException(SerializationInfo info, StreamingContext context) : base(info, context)
        {
            EntityName = string.Empty;
        }

        private void Init()
        {
            ErrorCode = Music_ERROR_CODE;
            HttpStatusCode = 400;
        }
    }
}
